"""phase11: scene annotations and background audio

Revision ID: 1f37b01d244b
Revises: 41e76eb52506
Create Date: 2026-09-20 15:32:28.490367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f37b01d244b'
down_revision: Union[str, None] = '41e76eb52506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_annotations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('anchor_x', sa.Float(), nullable=False),
    sa.Column('anchor_y', sa.Float(), nullable=False),
    sa.Column('anchor_z', sa.Float(), nullable=False),
    sa.Column('style', sa.String(length=30), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('text_content', sa.String(length=10000), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('text_color', sa.String(length=20), nullable=False),
    sa.Column('text_size', sa.Integer(), nullable=False),
    sa.Column('fov', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['assets.id'], name=op.f('fk_scene_annotations_media_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_annotations_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_annotations'))
    )
    op.create_index('ix_scene_annotations_scene_id', 'scene_annotations', ['scene_id'], unique=False)
    op.create_index('ix_scene_annotations_scene_order', 'scene_annotations', ['scene_id', 'order_index'], unique=False)
    op.add_column('scene_presentations', sa.Column('background_audio_asset_id', sa.Uuid(), nullable=True))
    op.add_column('scene_presentations', sa.Column('background_audio_volume', sa.Float(), nullable=False))
    op.add_column('scene_presentations', sa.Column('background_audio_loop', sa.Boolean(), nullable=False))
    op.add_column('scene_presentations', sa.Column('background_audio_enabled', sa.Boolean(), nullable=False))
    op.create_foreign_key(op.f('fk_scene_presentations_background_audio_asset_id_assets'), 'scene_presentations', 'assets', ['background_audio_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scene_presentations_background_audio_asset_id_assets'), 'scene_presentations', type_='foreignkey')
    op.drop_column('scene_presentations', 'background_audio_enabled')
    op.drop_column('scene_presentations', 'background_audio_loop')
    op.drop_column('scene_presentations', 'background_audio_volume')
    op.drop_column('scene_presentations', 'background_audio_asset_id')
    op.drop_index('ix_scene_annotations_scene_order', table_name='scene_annotations')
    op.drop_index('ix_scene_annotations_scene_id', table_name='scene_annotations')
    op.drop_table('scene_annotations')
    # ### end Alembic commands ###
