"""phase10: scene authoring core (presentations + viewpoints)

Revision ID: 41e76eb52506
Revises: f0c8d7e6a5b4
Create Date: 2026-09-20 13:19:22.340826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41e76eb52506'
down_revision: Union[str, None] = 'f0c8d7e6a5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_viewpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fov', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_viewpoints_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_viewpoints'))
    )
    op.create_index('ix_scene_viewpoints_scene_id', 'scene_viewpoints', ['scene_id'], unique=False)
    op.create_index('ix_scene_viewpoints_scene_order', 'scene_viewpoints', ['scene_id', 'order_index'], unique=False)
    op.create_table('scene_presentations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('world_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('world_rotation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('world_scale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initial_camera_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initial_camera_target', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('initial_camera_fov', sa.Float(), nullable=True),
    sa.Column('background_type', sa.String(length=20), nullable=False),
    sa.Column('background_color', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('background_asset_id', sa.Uuid(), nullable=True),
    sa.Column('background_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['background_asset_id'], ['assets.id'], name=op.f('fk_scene_presentations_background_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cover_asset_id'], ['assets.id'], name=op.f('fk_scene_presentations_cover_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_scene_presentations_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scene_presentations')),
    sa.UniqueConstraint('scene_id', name=op.f('uq_scene_presentations_scene_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scene_presentations')
    op.drop_index('ix_scene_viewpoints_scene_order', table_name='scene_viewpoints')
    op.drop_index('ix_scene_viewpoints_scene_id', table_name='scene_viewpoints')
    op.drop_table('scene_viewpoints')
    # ### end Alembic commands ###
